version: '3'
services:
  spring-project:
    build: ./
    ports:
      - '8080:8080'
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5434/database
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=changeme
    ports:
      - '5434:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: