spring:
  application:
    name: springboot-react-project
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATASOURCE_URL}
    username: admin
    password: changeme
accessTokenSecret: testAccessTokenSecret
refreshTokenSecret: testRefreshTokenSecret
accessTokenExpirationMinutes: 1
refreshTokenExpirationDays: 2

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG